### ISSUE TITLE
Not working Papermc 1.16.4

### ISSUE THREAD

**Issue by nanitook** [7kasper/TrainCartsDestinationSelector#2]
![image](https://github.com/user-attachments/assets/892c7864-324e-4c47-bce0-18f96fc311d6)

using latest build available (416) doesn't work either
is 1.16.4 supported?

**Comment by 7kasper** [comment]
Hey! Mojang changed the way signs work quite significantly in 1.20. You can use an older build for 1.16.4 though. Try https://github.com/7kasper/TrainCartsDestinationSelector/releases/tag/0.2
Feel free to let me know if you have other problems!
